--CONFIG------------------------------------------------------
pcall(require, "luarocks.loader")
require("awful.autofocus")
require("awful.hotkeys_popup.keys")
require("misc.variables")
require("misc.errors")
require("ui.bar")
require("client.rules")
require("keymaps.globalkeys")
require("misc.layout")
require("misc.autostart")
